export const PERMISSIONS = Object.freeze({
    CATEGORY: {
        INDEX: "Category Index",
        STORE: "Category Store",
        UPDATE: "Category Update",
        EDIT: "Category Edit",
        DELETE: "Category Delete",
        SEARCH: "Category Search",
        EXPORT: "Category Export",
        BULK_DELETE: "Category Bulk Delete",
        BULK_RESTORE: "Category Bulk Restore",
    },

    BRAND: {
        INDEX: "Brand Index",
        STORE: "Brand Store",
        UPDATE: "Brand Update",
        EDIT: "Brand Edit",
        DELETE: "Brand Delete",
        SEARCH: "Brand Search",
        EXPORT: "Brand Export",
        BULK_DELETE: "Brand Bulk Delete",
        BULK_RESTORE: "Brand Bulk Restore",
    },

    TAG: {
        INDEX: "Tag Index",
        STORE: "Tag Store",
        UPDATE: "Tag Update",
        EDIT: "Tag Edit",
        DELETE: "Tag Delete",
        SEARCH: "Tag Search",
        EXPORT: "Tag Export",
        BULK_DELETE: "Tag Bulk Delete",
        BULK_RESTORE: "Tag Bulk Restore",
    },

    TAX: {
        INDEX: "Tax Index",
        STORE: "Tax Store",
        UPDATE: "Tax Update",
        EDIT: "Tax Edit",
        DELETE: "Tax Delete",
        SEARCH: "Tax Search",
        EXPORT: "Tax Export",
        BULK_DELETE: "Tax Bulk Delete",
        BULK_RESTORE: "Tax Bulk Restore",
    },

    PAYMENT_METHOD: {
        INDEX: "Payment Methods Index",
        STORE: "Payment Methods Store",
        UPDATE: "Payment Methods Update",
        EDIT: "Payment Methods Edit",
        DELETE: "Payment Methods Delete",
        SEARCH: "Payment Methods Search",
        EXPORT: "Payment Methods Export",
        BULK_DELETE: "Payment Methods Bulk Delete",
        BULK_RESTORE: "Payment Methods Bulk Restore",
    },

    PRODUCT: {
        INDEX: "Product Index",
        STORE: "Product Store",
        UPDATE: "Product Update",
        EDIT: "Product Edit",
        DELETE: "Product Delete",
        MOVEMENT: "Product Movement",
        SEARCH: "Product Search",
        EXPORT: "Product Export",
        BULK_DELETE: "Product Bulk Delete",
        BULK_RESTORE: "Product Bulk Restore",
    },

    POS: {
        INDEX: "POS Index",
    },

    ORDER: {
        INDEX: "Order Index",
        VIEW: "Order View",
        INVOICE: "Order Invoice",
        COMPLETE: "Order Complete",
        VOID: "Order Void",
    },

    ROLE: {
        INDEX: "Role Index",
        STORE: "Role Store",
        UPDATE: "Role Update",
        EDIT: "Role Edit",
        DELETE: "Role Delete",
        SEARCH: "Role Search",
        EXPORT: "Role Export",
        BULK_DELETE: "Role Bulk Delete",
        BULK_RESTORE: "Role Bulk Restore",
    },

    PERMISSION: {
        INDEX: "Permission Index",
        STORE: "Permission Store",
    },

    USER: {
        INDEX: "User Index",
        STORE: "User Store",
        UPDATE: "User Update",
        EDIT: "User Edit",
        DELETE: "User Delete",
        SEARCH: "User Search",
        EXPORT: "User Export",
        BULK_DELETE: "User Bulk Delete",
        BULK_RESTORE: "User Bulk Restore",
    },

    BRANCH: {
        INDEX: "Branch Index",
        STORE: "Branch Store",
        UPDATE: "Branch Update",
        EDIT: "Branch Edit",
        DELETE: "Branch Delete",
        SEARCH: "Branch Search",
        EXPORT: "Branch Export",
        BULK_DELETE: "Branch Bulk Delete",
        BULK_RESTORE: "Branch Bulk Restore",
    },

    WAREHOUSE: {
        INDEX: "Warehouse Index",
        STORE: "Warehouse Store",
        UPDATE: "Warehouse Update",
        EDIT: "Warehouse Edit",
        DELETE: "Warehouse Delete",
        SEARCH: "Warehouse Search",
        EXPORT: "Warehouse Export",
        BULK_DELETE: "Warehouse Bulk Delete",
        BULK_RESTORE: "Warehouse Bulk Restore",
    },

    BASE_UNIT: {
        INDEX: "Base Unit Index",
        STORE: "Base Unit Store",
        UPDATE: "Base Unit Update",
        EDIT: "Base Unit Edit",
        DELETE: "Base Unit Delete",
        SEARCH: "Base Unit Search",
        EXPORT: "Base Unit Export",
        BULK_DELETE: "Base Unit Bulk Delete",
        BULK_RESTORE: "Base Unit Bulk Restore",
    },

    UNIT: {
        INDEX: "Unit Index",
        STORE: "Unit Store",
        UPDATE: "Unit Update",
        EDIT: "Unit Edit",
        DELETE: "Unit Delete",
        SEARCH: "Unit Search",
        EXPORT: "Unit Export",
        BULK_DELETE: "Unit Bulk Delete",
        BULK_RESTORE: "Unit Bulk Restore",
    },

    SUPPLIER: {
        INDEX: "Supplier Index",
        STORE: "Supplier Store",
        UPDATE: "Supplier Update",
        EDIT: "Supplier Edit",
        DELETE: "Supplier Delete",
        SEARCH: "Supplier Search",
        EXPORT: "Supplier Export",
        BULK_DELETE: "Supplier Bulk Delete",
        BULK_RESTORE: "Supplier Bulk Restore",
    },

    CUSTOMER: {
        INDEX: "Customer Index",
        STORE: "Customer Store",
        UPDATE: "Customer Update",
        EDIT: "Customer Edit",
        DELETE: "Customer Delete",
        SEARCH: "Customer Search",
        EXPORT: "Customer Export",
        BULK_DELETE: "Customer Bulk Delete",
        BULK_RESTORE: "Customer Bulk Restore",
    },

    EXPENSE_CATEGORY: {
        INDEX: "Expense Categories Index",
        STORE: "Expense Categories Store",
        UPDATE: "Expense Categories Update",
        EDIT: "Expense Categories Edit",
        DELETE: "Expense Categories Delete",
        SEARCH: "Expense Categories Search",
        EXPORT: "Expense Categories Export",
        BULK_DELETE: "Expense Categories Bulk Delete",
        BULK_RESTORE: "Expense Categories Bulk Restore",
    },

    EXPENSE: {
        INDEX: "Expense Index",
        STORE: "Expense Store",
        UPDATE: "Expense Update",
        EDIT: "Expense Edit",
        DELETE: "Expense Delete",
        SEARCH: "Expense Search",
        EXPORT: "Expense Export",
        BULK_DELETE: "Expense Bulk Delete",
        BULK_RESTORE: "Expense Bulk Restore",
    },

    COUNTRY: {
        INDEX: "Country Index",
        STORE: "Country Store",
        UPDATE: "Country Update",
        EDIT: "Country Edit",
        DELETE: "Country Delete",
        SEARCH: "Country Search",
        EXPORT: "Country Export",
        BULK_DELETE: "Country Bulk Delete",
        BULK_RESTORE: "Country Bulk Restore",
    },

    SETTING: {
        INDEX: "Setting Index",
    },
});
